### PR TITLE
Rails app with models and some basic tests

### PR DESCRIPTION
**Pull request by mabid**
Basic Rails app with models

Member
Error
Message
User
Website

I am little confused about the relations between all of them and would like input if we need to modify them to better fit our needs

### CODE REVIEW

**Comment by Chocksy** [comment]
@mabid  you are right `Error` is not right we should rename that to `Issue` seems good? I would go for issue instead of report because we will probably use the same model when we will store exception details too. So issue seems more general.

**Comment by mabid** [comment]
`Issue` Sounds good, I'll change that. Can you review the relations between models

`Member` -> `has_many` (`Websites`)

`User` -> `belongs_to`(`Website`), `has_many`(`Issues`)

`Website` -> `belongs_to (User)`, `has_many(Users)`, `has_many(Issues`) through `Users`

`Issue -> belongs_to (User),`delegates(website)`to`User`

`Message` -> `belongs_to`(`Issue`), `delegates(User)` to `Issue`

What if same issue is reported by different users ? do we treat that as separate error or have a procedure to merge it or for now we are ignoring this ?

We have `User->belongs_to(Website)`, a `user` is identified by `email`, if the same user reports another `issue` from a different `website` do we treat that as a separate user or same user ?

**Comment by Chocksy** [comment]
- Relations we should do a change in this way:
  - issues have many messages
  - user has many issues
  - issues have many users  **(so we need another model to provide for the many_to_many relation _user_issues_ maybe?)**
- About duplicate issues we should use the issue message that is posted via the JS library as a unique key constraint.  
- We have to think of Users as users of that website we won't be offering users a login mechanism or any kind of way to report errors in other websites at least not for now. This in a way is what is different from what others are doing as they are probably not holding users in a separate table.

**Comment by Chocksy** [comment]
@mabid it's all good? Let me know if you need any help. I'll start to have some time next week probably so i would love to merge this and improve upon it.

**Comment by mabid** [comment]
@Chocksy I'll be improving this over the weekend and will try to add API authentication on top so we can get started with the webapp as well.

**Comment by Chocksy** [comment]
@mabid sweet. :D

**Comment by mabid** [comment]
@Chocksy check it out, I fixed some model relations as pointed out, added token based auth that would go well with AngularJS modlue ng-token-auth

**Comment by Chocksy** [comment]
@mabid ok this can go into master we'll focus next on having the controllers for signup and sessions.

**Pull request merged**
